#!/bin/bash
NAME="example-1" \
REPORT_FILENAME=$NAME"-Report" \
PLOT_FILENAME=$NAME"-Plot" \
N_STK=10 \
N_MAN=2 \
LOCKTIME=144 \
NUMBER_VAULTS=5 \
REFILL_EXCESS=5 \
REFILL_PERIOD=$((144 * 7)) \
SPEND_RATE=0.5 \
UNVAULT_RATE=0.5 \
INVALID_SPEND_RATE="0.05" \
DELEGATE_RATE=0.5 \
BALANCE=true \
CUM_OP_COST=true \
RISK_TIME=true \
DIVERGENCE=true \
OP_COST=false \
OVERPAYMENTS=true \
RISK_STATUS=false \
FB_COINS_DIST=false \
python3 main.py
